import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
const source = new URL("../src/lib/chess/", import.meta.url),
  dest = new URL("../supabase/functions/_shared/chess/", import.meta.url);
const check = process.argv.includes("--check");
async function sync(path = "") {
  const entries = await readdir(new URL(path, source), { withFileTypes: true });
  const expected = [];
  for (const entry of entries) {
    if (entry.name.endsWith(".test.ts")) continue;
    const relative = join(path, entry.name);
    expected.push(entry.name);
    if (entry.isDirectory()) {
      await sync(`${relative}/`);
      continue;
    }
    if (!entry.name.endsWith(".ts")) throw new Error(`Unexpected engine asset: ${relative}`);
    const text = await readFile(new URL(relative, source), "utf8");
    for (const match of text.matchAll(/(?:from\s+|import\s*)["']([^"']+)["']/g))
      if (!match[1].startsWith("."))
        throw new Error(`Engine must remain runtime-independent: ${relative}`);
    const generated = `// GENERATED by pnpm chess:sync. Edit src/lib/chess/${relative} instead.\n${text}`;
    const target = new URL(relative, dest);
    if (check) {
      if ((await readFile(target, "utf8")) !== generated)
        throw new Error(`Stale Edge engine: ${relative}`);
    } else {
      await mkdir(new URL(path || ".", dest), { recursive: true });
      await writeFile(target, generated);
    }
  }
  if (check)
    for (const entry of await readdir(new URL(path, dest)))
      if (!expected.includes(entry))
        throw new Error(`Unexpected Edge engine file: ${join(path, entry)}`);
}
await sync();
console.log(check ? "Edge engine matches canonical source." : "Edge engine synchronized.");
